import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainHeader from "./components/header/main-header";
import FriendSideBar from "./components/friends-sidebar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Real-time Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-white text-grey-700">
      <body className="h-screen">
        <MainHeader></MainHeader>
      <FriendSideBar></FriendSideBar>
        
        {children}
      </body>
    </html>
  );
}
